### ISSUE TITLE
Cannot use large files with high number of engines

### ISSUE THREAD

**Issue by harpratap** [rakutentech/shibuya#2]
Since the controller reads everything in memory before sending off the test files to engines, the size of each test file and subsequently the number of engines used by such plans is limited by the memory assigned to controller. 

For instance a 100MB txt file with 20 engines will easily kill the controller with 2GB limits.

**Comment by harpratap** [comment]
The proposed solution is to let the engines fetch the test plans on their own instead of the controller. The controller can just pass the metadata of the files to each engine, they can split the files if needed based on this info.

**Comment by iandyh** [comment]
One important thing: User should be able to select the storage options, like Nexus and GCP.

**Comment by harpratap** [comment]
@iandyh Okay that is a pretty big change in requirements. We will need to keep a track of which files are stored where and migration for existing users will not be trivial anymore

**Comment by iandyh** [comment]
@harpratap oh I mean the user here is Shibuya project user. Not Shibuya user. Sorry for the confusion.

**Comment by harpratap** [comment]
This can be configured here - https://github.com/rakutentech/shibuya/blob/master/shibuya/config/init.go#L75 so it will automatically pick up the correct storage based on config.json

**Comment by iandyh** [comment]
Yes, I am aware of that. i want shibuya-agent to avoid GCP specific code.

**Comment by harpratap** [comment]
Hmm not sure how that would be possible. Agent has to be able to read from all store types now
